{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h1>Project<h1>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>sentiment</th>\n",
       "      <th>review</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>5814_8</td>\n",
       "      <td>1</td>\n",
       "      <td>With all this stuff going down at the moment w...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2381_9</td>\n",
       "      <td>1</td>\n",
       "      <td>\\The Classic War of the Worlds\\\" by Timothy Hi...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>7759_3</td>\n",
       "      <td>0</td>\n",
       "      <td>The film starts with a manager (Nicholas Bell)...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3630_4</td>\n",
       "      <td>0</td>\n",
       "      <td>It must be assumed that those who praised this...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>9495_8</td>\n",
       "      <td>1</td>\n",
       "      <td>Superbly trashy and wondrously unpretentious 8...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       id  sentiment                                             review\n",
       "0  5814_8          1  With all this stuff going down at the moment w...\n",
       "1  2381_9          1  \\The Classic War of the Worlds\\\" by Timothy Hi...\n",
       "2  7759_3          0  The film starts with a manager (Nicholas Bell)...\n",
       "3  3630_4          0  It must be assumed that those who praised this...\n",
       "4  9495_8          1  Superbly trashy and wondrously unpretentious 8..."
      ]
     },
     "execution_count": 45,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "df = pd.read_csv('imdb.tsv',sep = '\\t')\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def Punctuation(string): \n",
    "  \n",
    "    # punctuation marks \n",
    "    punctuations = '''!()-[]{};:'\"\\,<>./?@#$%^&*_~'''\n",
    "  \n",
    "    # traverse the given string and if any punctuation \n",
    "    # marks occur replace it with null \n",
    "    for x in string.lower(): \n",
    "        if x in punctuations: \n",
    "            string = string.replace(x, \"\") \n",
    "  \n",
    "    # Print string without punctuation \n",
    "    return string"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Time taken is 82.985392\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "\n",
    "start = time.time()\n",
    "reviews = np.array(df[list(df.columns)[2]])\n",
    "reviews = np.asarray(reviews)\n",
    "reviews = reviews[:1000]\n",
    "# remove punctuations\n",
    "proc = [Punctuation(review) for review in reviews]\n",
    "temp= \" bhakti \".join(proc)\n",
    "temp = temp.lower()\n",
    "proc = temp.split(\" bhakti \")\n",
    "\n",
    "temp = \" \".join(proc)\n",
    "unique = list(set(temp.split()))\n",
    "\n",
    "lexicon = {}\n",
    "\n",
    "all_words = temp.split()\n",
    "\n",
    "for word in unique:\n",
    "    lexicon[word] = all_words.count(word)\n",
    "\n",
    "print(\"Time taken is %f\" %(time.time() - start))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "new_dict2 = {}\n",
    "for i in lexicon.keys():\n",
    "    if (lexicon[i]>5):\n",
    "        new_dict2[i] = lexicon[i]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'complaint': 7,\n",
       " 'show': 256,\n",
       " 'girlfriend': 15,\n",
       " 'horribly': 6,\n",
       " 'triumph': 7,\n",
       " 'worthy': 8,\n",
       " 'slapstick': 7,\n",
       " '3d': 7,\n",
       " 'loved': 50,\n",
       " 'keitel': 8,\n",
       " 'most': 327,\n",
       " 'thugs': 8,\n",
       " 'energy': 25,\n",
       " 'all': 925,\n",
       " 'poor': 89,\n",
       " 'skill': 11,\n",
       " 'serious': 47,\n",
       " 'hold': 20,\n",
       " 'run': 43,\n",
       " 'tim': 12,\n",
       " 'conversation': 9,\n",
       " 'caine': 19,\n",
       " 'detective': 12,\n",
       " 'were': 424,\n",
       " 'zero': 15,\n",
       " 'rex': 7,\n",
       " 'reaction': 8,\n",
       " 'patience': 7,\n",
       " 'member': 11,\n",
       " 'san': 11,\n",
       " 'has': 655,\n",
       " 'annoyed': 6,\n",
       " 'structure': 10,\n",
       " 'uncle': 8,\n",
       " 'inane': 6,\n",
       " 'dr': 24,\n",
       " 'still': 195,\n",
       " 'format': 8,\n",
       " 'creepy': 27,\n",
       " 'poison': 7,\n",
       " 'damaged': 8,\n",
       " 'sorts': 8,\n",
       " 'facing': 7,\n",
       " 'numbers': 16,\n",
       " 'notbr': 6,\n",
       " 'and': 6469,\n",
       " 'record': 10,\n",
       " 'indeed': 32,\n",
       " 'rated': 16,\n",
       " 'tap': 7,\n",
       " 'side': 44,\n",
       " 'across': 46,\n",
       " 'highly': 40,\n",
       " 'highlights': 6,\n",
       " 'former': 16,\n",
       " 'directing': 32,\n",
       " 'sequences': 19,\n",
       " 'filmmaking': 17,\n",
       " 'memories': 10,\n",
       " 'sin': 6,\n",
       " 'efforts': 8,\n",
       " 'fully': 22,\n",
       " 'directly': 7,\n",
       " 'point': 120,\n",
       " 'blockbuster': 7,\n",
       " 'length': 17,\n",
       " 'best': 236,\n",
       " 'at': 918,\n",
       " 'begins': 22,\n",
       " 'essentially': 15,\n",
       " 'enjoyed': 59,\n",
       " 'hidden': 14,\n",
       " 'city': 55,\n",
       " 'bring': 41,\n",
       " 'purely': 10,\n",
       " 'ran': 12,\n",
       " 'satan': 7,\n",
       " 'superhero': 9,\n",
       " 'almost': 139,\n",
       " 'exciting': 25,\n",
       " 'sings': 6,\n",
       " 'add': 31,\n",
       " 'era': 35,\n",
       " 'directs': 6,\n",
       " 'shining': 6,\n",
       " 'meeting': 8,\n",
       " 'doc': 10,\n",
       " 'brings': 20,\n",
       " 'sports': 9,\n",
       " 'sinister': 6,\n",
       " 'chemistry': 25,\n",
       " 'being': 276,\n",
       " 'alcohol': 7,\n",
       " 'similar': 20,\n",
       " 'likes': 11,\n",
       " 'addition': 14,\n",
       " 'hardly': 18,\n",
       " 'threatens': 9,\n",
       " 'catches': 6,\n",
       " 'shes': 49,\n",
       " 'frequently': 9,\n",
       " 'adventure': 21,\n",
       " 'sexual': 35,\n",
       " 'silly': 30,\n",
       " 'americas': 7,\n",
       " 'cooper': 7,\n",
       " 'tom': 29,\n",
       " 'elses': 7,\n",
       " 'hunters': 12,\n",
       " 'down': 135,\n",
       " 'perfectly': 21,\n",
       " 'toilet': 7,\n",
       " 'bar': 15,\n",
       " 'brought': 39,\n",
       " 'mainstream': 11,\n",
       " 'spanish': 16,\n",
       " 'noticed': 11,\n",
       " 'hours': 34,\n",
       " 'joseph': 7,\n",
       " 'shows': 83,\n",
       " 'starring': 20,\n",
       " 'afghanistan': 6,\n",
       " 'christmas': 19,\n",
       " 'con': 8,\n",
       " 'jerry': 21,\n",
       " 'remain': 20,\n",
       " 'entertaining': 69,\n",
       " 'followed': 14,\n",
       " 'social': 30,\n",
       " 'personality': 11,\n",
       " 'becomes': 45,\n",
       " 'focus': 16,\n",
       " 'paintings': 8,\n",
       " 'doctor': 11,\n",
       " 'delight': 6,\n",
       " 'parody': 11,\n",
       " 'design': 14,\n",
       " 'couldve': 7,\n",
       " 'none': 43,\n",
       " 'trailer': 12,\n",
       " '1980s': 13,\n",
       " 'website': 7,\n",
       " 'head': 56,\n",
       " 'disaster': 13,\n",
       " 'rather': 136,\n",
       " 'reminds': 15,\n",
       " 'day': 98,\n",
       " 'deathtrap': 7,\n",
       " 'clearly': 39,\n",
       " 'proves': 11,\n",
       " 'james': 34,\n",
       " 'worldbr': 7,\n",
       " 'eyes': 51,\n",
       " 'admire': 8,\n",
       " 'unintentionally': 6,\n",
       " 'weve': 12,\n",
       " 'theater': 25,\n",
       " 'blue': 14,\n",
       " 'retired': 6,\n",
       " 'little': 231,\n",
       " 'sequel': 33,\n",
       " 'legs': 6,\n",
       " 'ironically': 7,\n",
       " 'introduction': 8,\n",
       " 'godfather': 6,\n",
       " 'led': 17,\n",
       " 'feeling': 42,\n",
       " 'trilogy': 10,\n",
       " 'christopher': 18,\n",
       " 'albert': 9,\n",
       " 'following': 27,\n",
       " 'relax': 8,\n",
       " 'chest': 6,\n",
       " 'hit': 36,\n",
       " '70s': 20,\n",
       " 'person': 55,\n",
       " 'places': 7,\n",
       " 'decades': 7,\n",
       " 'creative': 18,\n",
       " 'european': 9,\n",
       " 'literally': 17,\n",
       " 'cultures': 7,\n",
       " 'changes': 18,\n",
       " 'ladies': 18,\n",
       " 'expert': 11,\n",
       " 'stays': 13,\n",
       " 'amateurish': 11,\n",
       " 'eddie': 13,\n",
       " 'nomination': 6,\n",
       " 'seedy': 6,\n",
       " 'goofy': 6,\n",
       " 'audiencebr': 6,\n",
       " 'celluloid': 7,\n",
       " 'grade': 19,\n",
       " 'issues': 18,\n",
       " 'projects': 7,\n",
       " 'leaving': 21,\n",
       " 'brain': 11,\n",
       " 'judge': 18,\n",
       " 'including': 39,\n",
       " 'pain': 11,\n",
       " 'cultural': 11,\n",
       " 'forever': 15,\n",
       " 'april': 7,\n",
       " 'roger': 14,\n",
       " 'second': 69,\n",
       " 'brian': 8,\n",
       " '7': 23,\n",
       " 'japan': 9,\n",
       " 'conceived': 6,\n",
       " 'reality': 29,\n",
       " 'twists': 14,\n",
       " 'whats': 31,\n",
       " 'pretentious': 10,\n",
       " 'out': 623,\n",
       " 'actually': 148,\n",
       " 'black': 72,\n",
       " 'obsessed': 6,\n",
       " 'ned': 10,\n",
       " 'island': 9,\n",
       " 'comment': 26,\n",
       " 'an': 820,\n",
       " 'significant': 7,\n",
       " 'clean': 9,\n",
       " 'rise': 10,\n",
       " 'futuristic': 6,\n",
       " 'up': 484,\n",
       " 'clue': 7,\n",
       " 'cigarette': 6,\n",
       " 'yes': 54,\n",
       " 'watchbr': 6,\n",
       " 'macdonald': 6,\n",
       " 'unexpected': 14,\n",
       " 'flawless': 8,\n",
       " 'comedic': 12,\n",
       " 'wonderful': 50,\n",
       " 'robbery': 11,\n",
       " 'entertainment': 42,\n",
       " 'draw': 11,\n",
       " 'shakespeare': 9,\n",
       " 'failed': 28,\n",
       " 'fights': 9,\n",
       " 'investigation': 10,\n",
       " 'lying': 8,\n",
       " 'him': 324,\n",
       " 'fare': 8,\n",
       " 'stereotype': 6,\n",
       " 'made': 303,\n",
       " 'zenia': 11,\n",
       " 'schools': 10,\n",
       " 'majority': 13,\n",
       " 'blah': 14,\n",
       " 'rachel': 7,\n",
       " 'park': 8,\n",
       " 'america': 20,\n",
       " 'accused': 6,\n",
       " 'talks': 12,\n",
       " 'vincent': 6,\n",
       " 'into': 369,\n",
       " 'ms': 14,\n",
       " 'stinks': 6,\n",
       " 'flamenco': 10,\n",
       " 'coming': 39,\n",
       " 'spent': 21,\n",
       " 'god': 40,\n",
       " 'occasional': 12,\n",
       " 'subplots': 6,\n",
       " 'wall': 10,\n",
       " 'pointless': 20,\n",
       " 'sam': 18,\n",
       " 'potential': 25,\n",
       " 'remotely': 10,\n",
       " 'j': 10,\n",
       " 'matters': 10,\n",
       " 'spoilers': 17,\n",
       " 'stark': 7,\n",
       " 'vice': 7,\n",
       " 'emma': 7,\n",
       " 'resembles': 6,\n",
       " 'able': 44,\n",
       " 'flying': 9,\n",
       " 'word': 30,\n",
       " 'noriko': 8,\n",
       " 'calls': 16,\n",
       " 'intentionally': 7,\n",
       " 'victim': 8,\n",
       " 'innocence': 7,\n",
       " 'global': 12,\n",
       " 'persons': 7,\n",
       " 'brother': 29,\n",
       " 'sad': 36,\n",
       " 'starred': 7,\n",
       " 'comic': 45,\n",
       " 'harry': 8,\n",
       " 'intent': 6,\n",
       " 'channel': 14,\n",
       " 'state': 31,\n",
       " 'causes': 6,\n",
       " 'routine': 6,\n",
       " 'zombies': 34,\n",
       " 'national': 7,\n",
       " 'site': 7,\n",
       " 'job': 96,\n",
       " 'marquis': 8,\n",
       " 'chair': 9,\n",
       " 'cheesy': 24,\n",
       " 'aside': 16,\n",
       " 'chilling': 7,\n",
       " 'cook': 11,\n",
       " 'hindi': 7,\n",
       " 'page': 12,\n",
       " 'engaging': 11,\n",
       " 'supernatural': 8,\n",
       " 'pick': 20,\n",
       " 'flat': 33,\n",
       " 'intelligent': 16,\n",
       " 'turning': 24,\n",
       " 'strikes': 8,\n",
       " 'dialogs': 7,\n",
       " 'maugham': 6,\n",
       " 'shadows': 7,\n",
       " 'dialogue': 56,\n",
       " 'miss': 30,\n",
       " 'case': 65,\n",
       " 'friday': 7,\n",
       " '50s': 10,\n",
       " 'act': 40,\n",
       " 'year': 70,\n",
       " 'variety': 7,\n",
       " 'fourth': 8,\n",
       " 'oscar': 41,\n",
       " 'ridiculously': 6,\n",
       " 'few': 179,\n",
       " 'expectations': 16,\n",
       " 'opens': 6,\n",
       " 'wrapped': 7,\n",
       " 'replacement': 6,\n",
       " 'easier': 7,\n",
       " 'task': 7,\n",
       " 'hilarious': 35,\n",
       " 'contact': 6,\n",
       " 'cover': 26,\n",
       " 'lucky': 6,\n",
       " 'performances': 65,\n",
       " 'wow': 15,\n",
       " 'remainder': 6,\n",
       " 'gas': 8,\n",
       " 'leaves': 28,\n",
       " 'network': 11,\n",
       " 'slight': 7,\n",
       " 'babies': 6,\n",
       " 'dentist': 7,\n",
       " 'christy': 7,\n",
       " 'level': 37,\n",
       " 'values': 16,\n",
       " 'plots': 6,\n",
       " 'elena': 6,\n",
       " 'dynamic': 7,\n",
       " 'traditional': 10,\n",
       " 'perfect': 58,\n",
       " 'cousin': 7,\n",
       " 'assume': 8,\n",
       " 'california': 8,\n",
       " 'menacing': 8,\n",
       " 'received': 13,\n",
       " 'figures': 13,\n",
       " 'moore': 12,\n",
       " 'anime': 11,\n",
       " 'bed': 10,\n",
       " 'tears': 14,\n",
       " 'beneath': 8,\n",
       " 'no': 524,\n",
       " 'turner': 9,\n",
       " 'impression': 21,\n",
       " 'talked': 6,\n",
       " 'restaurant': 7,\n",
       " 'involvement': 7,\n",
       " 'attack': 13,\n",
       " 'fight': 52,\n",
       " 'may': 118,\n",
       " 'granted': 7,\n",
       " 'masterpiece': 27,\n",
       " 'nominated': 6,\n",
       " 'shoot': 18,\n",
       " 'fred': 9,\n",
       " 'soul': 14,\n",
       " 'childrens': 6,\n",
       " 'joe': 35,\n",
       " 'chasing': 7,\n",
       " 'expressions': 7,\n",
       " 'ma': 7,\n",
       " 'corny': 9,\n",
       " 'charming': 12,\n",
       " 'pair': 13,\n",
       " 'qualities': 7,\n",
       " 'alive': 13,\n",
       " 'thanks': 10,\n",
       " 'starting': 11,\n",
       " 'pasolini': 6,\n",
       " 'retarded': 7,\n",
       " 'theyd': 6,\n",
       " 'book': 100,\n",
       " 'simply': 73,\n",
       " 'niven': 6,\n",
       " 'relationships': 16,\n",
       " 'frank': 15,\n",
       " 'tierney': 8,\n",
       " 'random': 10,\n",
       " 'certain': 32,\n",
       " 'greatest': 32,\n",
       " 'couple': 66,\n",
       " 'maybe': 83,\n",
       " 'result': 27,\n",
       " 'game': 32,\n",
       " 'knocked': 9,\n",
       " 'cd': 10,\n",
       " 'wouldnt': 39,\n",
       " 'knew': 27,\n",
       " 'jazz': 6,\n",
       " 'taken': 31,\n",
       " 'count': 8,\n",
       " 'screen': 84,\n",
       " 'manages': 30,\n",
       " 'truth': 33,\n",
       " 'wonder': 43,\n",
       " 'began': 21,\n",
       " 'faith': 7,\n",
       " 'incredibly': 21,\n",
       " 'racial': 6,\n",
       " 'stinker': 6,\n",
       " 'minor': 16,\n",
       " 'cast': 155,\n",
       " 'population': 6,\n",
       " 'filmbr': 29,\n",
       " 'kids': 61,\n",
       " 'forced': 33,\n",
       " 'painful': 12,\n",
       " 'adults': 8,\n",
       " 'mindless': 6,\n",
       " 'amount': 20,\n",
       " 'altogether': 7,\n",
       " 'peoples': 12,\n",
       " 'powerful': 32,\n",
       " 'hes': 126,\n",
       " 'young': 141,\n",
       " 'idea': 68,\n",
       " 'fine': 49,\n",
       " 'nonstop': 7,\n",
       " 'unfortunate': 7,\n",
       " 'employed': 7,\n",
       " 'any': 287,\n",
       " 'usual': 47,\n",
       " 'build': 9,\n",
       " 'impossible': 13,\n",
       " 'dragon': 6,\n",
       " 'those': 194,\n",
       " 'flesh': 6,\n",
       " 'explanation': 8,\n",
       " 'center': 17,\n",
       " 'hero': 33,\n",
       " 'woods': 13,\n",
       " 'summary': 10,\n",
       " 'knife': 9,\n",
       " 'indiana': 8,\n",
       " 'comedy': 109,\n",
       " 'original': 126,\n",
       " 'awful': 61,\n",
       " 'realised': 7,\n",
       " 'couples': 6,\n",
       " 'reynolds': 7,\n",
       " 'study': 8,\n",
       " 'throat': 7,\n",
       " 'eventually': 29,\n",
       " 'waters': 7,\n",
       " 'emerge': 7,\n",
       " 'richardson': 7,\n",
       " 'emotionally': 11,\n",
       " 'stand': 25,\n",
       " 'fascinating': 13,\n",
       " 'paced': 11,\n",
       " 'acting': 251,\n",
       " 'trio': 8,\n",
       " 'suggested': 6,\n",
       " 'columbo': 12,\n",
       " 'cinema': 55,\n",
       " 'falk': 7,\n",
       " 'sexy': 21,\n",
       " 'members': 22,\n",
       " 'completely': 87,\n",
       " 'turkey': 6,\n",
       " 'already': 46,\n",
       " 'focused': 6,\n",
       " 'reasons': 15,\n",
       " 'occurs': 6,\n",
       " 'mathieu': 7,\n",
       " 'look': 144,\n",
       " 'powell': 11,\n",
       " 'thank': 22,\n",
       " 'fiction': 14,\n",
       " 'moves': 28,\n",
       " 'utter': 10,\n",
       " 'influence': 6,\n",
       " 'anna': 6,\n",
       " 'happening': 19,\n",
       " 'intensity': 8,\n",
       " 'boredom': 12,\n",
       " 'mysterious': 13,\n",
       " 'asking': 6,\n",
       " 'clothes': 9,\n",
       " 'niro': 6,\n",
       " 'accent': 16,\n",
       " 'hurt': 15,\n",
       " 'certainly': 56,\n",
       " 'shock': 11,\n",
       " 'subplot': 9,\n",
       " '60s': 8,\n",
       " 'path': 8,\n",
       " 'clever': 11,\n",
       " 'only': 464,\n",
       " 'natural': 21,\n",
       " 'tape': 12,\n",
       " 'tells': 39,\n",
       " 'ugly': 8,\n",
       " 'capable': 7,\n",
       " 'guess': 62,\n",
       " 'bill': 23,\n",
       " 'events': 29,\n",
       " 'denzel': 6,\n",
       " 'stuck': 14,\n",
       " 'child': 40,\n",
       " 'inept': 11,\n",
       " 'football': 7,\n",
       " 'gentle': 6,\n",
       " 'persona': 9,\n",
       " 'assumed': 8,\n",
       " 'from': 823,\n",
       " 'support': 19,\n",
       " 'theres': 124,\n",
       " 'boris': 7,\n",
       " 'fighting': 27,\n",
       " 'festival': 14,\n",
       " 'designed': 9,\n",
       " 'everyday': 8,\n",
       " 'incredible': 23,\n",
       " 'fat': 9,\n",
       " 'wood': 6,\n",
       " 'three': 94,\n",
       " 'lloyd': 6,\n",
       " 'aspect': 25,\n",
       " 'goes': 105,\n",
       " 'writerdirector': 7,\n",
       " 'credits': 36,\n",
       " 'storybr': 8,\n",
       " 'search': 17,\n",
       " 'compared': 24,\n",
       " 'after': 301,\n",
       " 'martial': 18,\n",
       " 'violence': 33,\n",
       " 'offered': 12,\n",
       " 'house': 85,\n",
       " 'setup': 8,\n",
       " 'makers': 19,\n",
       " 'portraying': 6,\n",
       " 'compelling': 18,\n",
       " 'lively': 7,\n",
       " 'happen': 40,\n",
       " 'clausen': 6,\n",
       " 'asks': 15,\n",
       " 'stick': 22,\n",
       " 'happened': 42,\n",
       " 'wants': 38,\n",
       " 'single': 41,\n",
       " 'truly': 77,\n",
       " 'forces': 15,\n",
       " 'research': 7,\n",
       " 'drug': 15,\n",
       " 'sit': 26,\n",
       " 'watch': 256,\n",
       " 'executive': 10,\n",
       " 'zombie': 45,\n",
       " 'becoming': 15,\n",
       " 'pile': 8,\n",
       " 'called': 50,\n",
       " 'red': 13,\n",
       " 'pot': 6,\n",
       " 'target': 9,\n",
       " 'everyones': 8,\n",
       " '1996': 10,\n",
       " 'exist': 7,\n",
       " 'wellbr': 12,\n",
       " 'stunts': 7,\n",
       " 'youd': 14,\n",
       " 'written': 64,\n",
       " 'warners': 11,\n",
       " 'always': 127,\n",
       " 'mirror': 9,\n",
       " 'okay': 25,\n",
       " 'ending': 106,\n",
       " 'witness': 7,\n",
       " 'mike': 15,\n",
       " 'very': 562,\n",
       " 'moments': 67,\n",
       " 'highlight': 7,\n",
       " 'reed': 12,\n",
       " 'competition': 6,\n",
       " 'test': 10,\n",
       " 'devoid': 6,\n",
       " 'magazine': 6,\n",
       " 'account': 7,\n",
       " 'deliver': 12,\n",
       " 'viewed': 8,\n",
       " 'kill': 44,\n",
       " 'stayed': 8,\n",
       " 'miscast': 6,\n",
       " 'crafted': 9,\n",
       " 'lesser': 9,\n",
       " 'workers': 8,\n",
       " 'dude': 8,\n",
       " 'footage': 22,\n",
       " 'box': 21,\n",
       " 'face': 65,\n",
       " 'ended': 19,\n",
       " 'student': 16,\n",
       " 'end': 201,\n",
       " 'horse': 6,\n",
       " 'lifestyle': 7,\n",
       " 'said': 70,\n",
       " 'winning': 16,\n",
       " 'annoying': 29,\n",
       " 'myself': 45,\n",
       " 'extra': 16,\n",
       " 'leading': 18,\n",
       " 'buck': 6,\n",
       " 'often': 66,\n",
       " 'pull': 16,\n",
       " 'appeal': 16,\n",
       " 'worked': 19,\n",
       " 'based': 47,\n",
       " 'surprise': 35,\n",
       " 'decided': 29,\n",
       " 'trip': 19,\n",
       " 'trouble': 22,\n",
       " 'caused': 6,\n",
       " 'trick': 9,\n",
       " 'unrealistic': 6,\n",
       " 'surprises': 7,\n",
       " 'momentum': 6,\n",
       " 'cliché': 21,\n",
       " '80': 6,\n",
       " 'robot': 6,\n",
       " 'academy': 9,\n",
       " 'battle': 25,\n",
       " 'bond': 12,\n",
       " 'over': 223,\n",
       " 'local': 42,\n",
       " 'gordon': 12,\n",
       " 'broadway': 10,\n",
       " 'forth': 6,\n",
       " 'cowboy': 20,\n",
       " 'killing': 21,\n",
       " 'color': 13,\n",
       " '1983': 6,\n",
       " 'allows': 16,\n",
       " 'court': 7,\n",
       " 'shocked': 7,\n",
       " 'braveheart': 7,\n",
       " 'roll': 16,\n",
       " 'scifi': 18,\n",
       " 'walken': 6,\n",
       " 'half': 48,\n",
       " 'stage': 45,\n",
       " 'mansion': 11,\n",
       " 'timothy': 6,\n",
       " 'facial': 7,\n",
       " 'union': 6,\n",
       " 'straight': 22,\n",
       " 'chose': 10,\n",
       " 'ho': 10,\n",
       " 'used': 70,\n",
       " 'thief': 6,\n",
       " 'memorable': 22,\n",
       " 'release': 40,\n",
       " 'describe': 16,\n",
       " 'doris': 6,\n",
       " 'away': 105,\n",
       " 'multiple': 8,\n",
       " 'dress': 6,\n",
       " 'nelson': 6,\n",
       " 'nicholson': 7,\n",
       " 'needed': 32,\n",
       " 'scream': 7,\n",
       " 'france': 6,\n",
       " 'mission': 13,\n",
       " 'puts': 15,\n",
       " 'sum': 7,\n",
       " 'individual': 11,\n",
       " 'dreadful': 18,\n",
       " 'supposedly': 12,\n",
       " 'watched': 84,\n",
       " 'encounter': 9,\n",
       " 'buster': 7,\n",
       " 'health': 6,\n",
       " 'represents': 6,\n",
       " 'on': 1315,\n",
       " 'jr': 8,\n",
       " 'arthur': 24,\n",
       " 'foreign': 6,\n",
       " 'discover': 11,\n",
       " '100': 12,\n",
       " 'painfully': 11,\n",
       " 'broadcast': 8,\n",
       " 'pieces': 18,\n",
       " 'date': 8,\n",
       " 'disbelief': 11,\n",
       " 'project': 18,\n",
       " 'go': 172,\n",
       " 'talent': 32,\n",
       " 'of': 5770,\n",
       " 'stops': 9,\n",
       " 'married': 23,\n",
       " 'bondage': 7,\n",
       " 'lame': 33,\n",
       " 'viewers': 39,\n",
       " 'its': 984,\n",
       " 'sword': 9,\n",
       " 'rule': 7,\n",
       " 'previous': 20,\n",
       " 'upon': 36,\n",
       " 'flynn': 9,\n",
       " 'rocket': 7,\n",
       " 'keeps': 23,\n",
       " 'had': 466,\n",
       " 'borrowed': 7,\n",
       " 'urban': 6,\n",
       " 'view': 40,\n",
       " 'character': 251,\n",
       " 'anger': 8,\n",
       " 'identity': 14,\n",
       " 'brilliant': 50,\n",
       " 'moody': 7,\n",
       " 'visiting': 6,\n",
       " 'runs': 17,\n",
       " 'anymore': 10,\n",
       " 'greater': 8,\n",
       " 'oliver': 7,\n",
       " 'mean': 59,\n",
       " 'breaking': 12,\n",
       " 'buddy': 8,\n",
       " 'script': 107,\n",
       " 'onebr': 9,\n",
       " 'laugh': 47,\n",
       " 'boxing': 7,\n",
       " 'chick': 11,\n",
       " 'sat': 7,\n",
       " 'whilst': 16,\n",
       " 'playing': 53,\n",
       " 'present': 25,\n",
       " 'korean': 7,\n",
       " 'opportunity': 17,\n",
       " 'they': 715,\n",
       " 'bit': 105,\n",
       " 'edward': 8,\n",
       " 'became': 14,\n",
       " 'aspects': 10,\n",
       " 'cross': 6,\n",
       " 'late': 44,\n",
       " 'noble': 6,\n",
       " 'purpose': 11,\n",
       " 'whenever': 8,\n",
       " 'accept': 15,\n",
       " 'examples': 9,\n",
       " 'ear': 6,\n",
       " 'guilt': 8,\n",
       " 'big': 131,\n",
       " 'purchase': 7,\n",
       " 'jeremy': 7,\n",
       " 'horrific': 7,\n",
       " 'pay': 29,\n",
       " 'image': 12,\n",
       " 'theatrical': 11,\n",
       " 'wait': 26,\n",
       " 'really': 463,\n",
       " 'onto': 15,\n",
       " 'saw': 134,\n",
       " 'remake': 27,\n",
       " 'winters': 11,\n",
       " 'occasionally': 10,\n",
       " 'caring': 8,\n",
       " 'wooden': 16,\n",
       " 'scale': 6,\n",
       " 'harvey': 7,\n",
       " 'jane': 25,\n",
       " 'fancy': 7,\n",
       " 'gives': 54,\n",
       " 'visually': 11,\n",
       " 'racist': 6,\n",
       " 'scared': 12,\n",
       " 'super': 13,\n",
       " 'within': 40,\n",
       " 'marriage': 13,\n",
       " 'bureau': 6,\n",
       " 'longer': 12,\n",
       " 'whatsoever': 19,\n",
       " 'fifteen': 9,\n",
       " 'communist': 12,\n",
       " 'street': 22,\n",
       " 'ill': 44,\n",
       " 'drama': 50,\n",
       " 'lily': 7,\n",
       " 'suspect': 9,\n",
       " 'ad': 6,\n",
       " 'warn': 6,\n",
       " 'track': 11,\n",
       " 'changing': 10,\n",
       " 'returns': 6,\n",
       " 'somehow': 26,\n",
       " 'lets': 46,\n",
       " 'with': 1854,\n",
       " 'jones': 16,\n",
       " 'convey': 8,\n",
       " 'fell': 15,\n",
       " 'lawler': 6,\n",
       " 'terribly': 8,\n",
       " 'o': 10,\n",
       " 'picks': 7,\n",
       " 'setting': 30,\n",
       " 'college': 19,\n",
       " 'florida': 6,\n",
       " 'la': 22,\n",
       " 'hood': 9,\n",
       " 'rest': 75,\n",
       " 'executed': 10,\n",
       " 'blacks': 7,\n",
       " 'cheated': 7,\n",
       " 'jean': 15,\n",
       " 'having': 99,\n",
       " 'oneliners': 11,\n",
       " 'appearance': 20,\n",
       " 'decides': 25,\n",
       " 'sense': 93,\n",
       " 'every': 144,\n",
       " 'hoods': 6,\n",
       " 'ron': 13,\n",
       " 'develop': 8,\n",
       " 'spoilerbr': 6,\n",
       " 'suspense': 26,\n",
       " 'falls': 35,\n",
       " 'watching': 171,\n",
       " 'cruel': 7,\n",
       " 'extremely': 32,\n",
       " 'games': 8,\n",
       " 'satire': 24,\n",
       " 'met': 17,\n",
       " 'drag': 9,\n",
       " 'todays': 11,\n",
       " 'importance': 6,\n",
       " 'share': 6,\n",
       " 'opinion': 37,\n",
       " 'fairy': 8,\n",
       " 'continuity': 12,\n",
       " 'police': 52,\n",
       " 'besides': 11,\n",
       " 'jeff': 12,\n",
       " 'secondly': 6,\n",
       " 'afford': 9,\n",
       " 'bob': 11,\n",
       " 'fox': 9,\n",
       " 'future': 31,\n",
       " 'shame': 20,\n",
       " 'manipulative': 6,\n",
       " 'inspiration': 9,\n",
       " 'film': 1538,\n",
       " 'order': 49,\n",
       " 'porn': 14,\n",
       " 'development': 25,\n",
       " 'younger': 23,\n",
       " 'use': 73,\n",
       " 'war': 88,\n",
       " 'glover': 7,\n",
       " 'hideous': 7,\n",
       " 'killers': 12,\n",
       " 'constant': 9,\n",
       " 'exists': 8,\n",
       " 'complain': 6,\n",
       " 'female': 30,\n",
       " 'connected': 7,\n",
       " 'london': 23,\n",
       " 'disney': 16,\n",
       " 'bette': 9,\n",
       " 'kate': 7,\n",
       " 'did': 250,\n",
       " 'hurts': 7,\n",
       " 'works': 49,\n",
       " 'collection': 18,\n",
       " 'drivel': 7,\n",
       " 'knowing': 23,\n",
       " 'hate': 24,\n",
       " 'capture': 13,\n",
       " 'dear': 9,\n",
       " 'seem': 80,\n",
       " 'round': 8,\n",
       " 'trying': 90,\n",
       " 'millions': 6,\n",
       " 'steps': 9,\n",
       " 'lose': 17,\n",
       " 'crouse': 7,\n",
       " 'jack': 26,\n",
       " 'candy': 17,\n",
       " 'corbett': 9,\n",
       " 'normal': 22,\n",
       " 'disappointment': 17,\n",
       " 'cost': 10,\n",
       " 'alan': 8,\n",
       " 'bat': 14,\n",
       " 'legendary': 12,\n",
       " 'lot': 161,\n",
       " 'creates': 7,\n",
       " 'ben': 29,\n",
       " 'described': 9,\n",
       " 'regular': 8,\n",
       " 'foul': 6,\n",
       " 'unhinged': 7,\n",
       " 'finish': 19,\n",
       " 'duke': 6,\n",
       " 'thrown': 12,\n",
       " 'david': 45,\n",
       " 'stars': 60,\n",
       " 'come': 118,\n",
       " 'difference': 24,\n",
       " 'tv': 108,\n",
       " 'complex': 14,\n",
       " 'accident': 11,\n",
       " 'mgm': 6,\n",
       " 'substance': 9,\n",
       " 'classes': 9,\n",
       " 'mr': 58,\n",
       " 'allow': 13,\n",
       " 'irritating': 7,\n",
       " 'wwii': 6,\n",
       " 'bunch': 38,\n",
       " 'extreme': 14,\n",
       " 'unknown': 12,\n",
       " 'spend': 24,\n",
       " 'goldie': 7,\n",
       " 'change': 46,\n",
       " 'real': 137,\n",
       " 'front': 14,\n",
       " 'butt': 9,\n",
       " 'filming': 16,\n",
       " 'sid': 7,\n",
       " 'somewhere': 23,\n",
       " 'base': 11,\n",
       " 'seen': 235,\n",
       " 'lighting': 22,\n",
       " 'bringing': 8,\n",
       " 'jon': 18,\n",
       " 'say': 211,\n",
       " 'cold': 20,\n",
       " 'collector': 8,\n",
       " 'considering': 27,\n",
       " '1': 61,\n",
       " 'stories': 55,\n",
       " 'nonsense': 14,\n",
       " 'technically': 9,\n",
       " 'mary': 32,\n",
       " 'hill': 11,\n",
       " 'graphic': 10,\n",
       " 'commercial': 13,\n",
       " 'risk': 7,\n",
       " 'tour': 8,\n",
       " 'brigham': 7,\n",
       " 'crash': 6,\n",
       " 'wang': 14,\n",
       " 'email': 6,\n",
       " 'sudden': 12,\n",
       " 'dealt': 11,\n",
       " 'superior': 12,\n",
       " 'outstanding': 14,\n",
       " 'joan': 11,\n",
       " 'repeated': 10,\n",
       " 'protagonist': 7,\n",
       " 'lake': 7,\n",
       " 'appalling': 7,\n",
       " 'win': 20,\n",
       " 'heavy': 18,\n",
       " 'sleep': 12,\n",
       " 'ambitious': 7,\n",
       " 'bergman': 15,\n",
       " 'current': 7,\n",
       " 'americans': 21,\n",
       " 'randy': 6,\n",
       " 'environment': 8,\n",
       " 'bore': 7,\n",
       " 'santa': 14,\n",
       " 'imaginative': 6,\n",
       " 'profound': 7,\n",
       " 'ages': 14,\n",
       " 'dust': 6,\n",
       " 'daughters': 13,\n",
       " 'heartwarming': 7,\n",
       " ...}"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "new_dict2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "def final(S): #S is a string\n",
    "    S = S.lower()\n",
    "    S = Punctuation(S)\n",
    "    S1 = S.split()\n",
    "    unique = list(set(S1))\n",
    "    ret = dict.fromkeys(new_dict2, 0)\n",
    "    ret['misc'] = 0\n",
    "    for word in unique:\n",
    "        if word in ret.keys():\n",
    "            ret[word] = S1.count(word)\n",
    "        else:\n",
    "            ret['misc'] += 1\n",
    "    ret = list(ret.values())\n",
    "    return ret"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "final_input = np.zeros([1000,len(new_dict2.keys())+1])\n",
    "for i in range(1000):\n",
    "    final_input[i] = final(reviews[i])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(1000, 3559)"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "final_input.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "y = np.array(df[list(df.columns)[1]])\n",
    "y = y[0:1000]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.cast instead.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.\n",
      "  \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/100\n",
      "1000/1000 [==============================] - 2s 2ms/step - loss: 0.6914 - acc: 0.5610\n",
      "Epoch 2/100\n",
      "1000/1000 [==============================] - 1s 571us/step - loss: 0.5886 - acc: 0.7590\n",
      "Epoch 3/100\n",
      "1000/1000 [==============================] - 1s 561us/step - loss: 0.4850 - acc: 0.8830\n",
      "Epoch 4/100\n",
      "1000/1000 [==============================] - 1s 549us/step - loss: 0.3756 - acc: 0.9310\n",
      "Epoch 5/100\n",
      "1000/1000 [==============================] - 1s 623us/step - loss: 0.2712 - acc: 0.9680\n",
      "Epoch 6/100\n",
      "1000/1000 [==============================] - 1s 537us/step - loss: 0.1933 - acc: 0.9910\n",
      "Epoch 7/100\n",
      "1000/1000 [==============================] - 1s 555us/step - loss: 0.1472 - acc: 0.9970\n",
      "Epoch 8/100\n",
      "1000/1000 [==============================] - 1s 741us/step - loss: 0.1174 - acc: 1.0000\n",
      "Epoch 9/100\n",
      "1000/1000 [==============================] - 1s 542us/step - loss: 0.0956 - acc: 1.0000\n",
      "Epoch 10/100\n",
      "1000/1000 [==============================] - 1s 541us/step - loss: 0.0783 - acc: 1.0000\n",
      "Epoch 11/100\n",
      "1000/1000 [==============================] - 1s 511us/step - loss: 0.0650 - acc: 1.0000\n",
      "Epoch 12/100\n",
      "1000/1000 [==============================] - 1s 526us/step - loss: 0.0550 - acc: 1.0000\n",
      "Epoch 13/100\n",
      "1000/1000 [==============================] - 1s 561us/step - loss: 0.0473 - acc: 1.0000\n",
      "Epoch 14/100\n",
      "1000/1000 [==============================] - 1s 692us/step - loss: 0.0413 - acc: 1.0000\n",
      "Epoch 15/100\n",
      "1000/1000 [==============================] - 1s 598us/step - loss: 0.0364 - acc: 1.0000\n",
      "Epoch 16/100\n",
      "1000/1000 [==============================] - 1s 590us/step - loss: 0.0324 - acc: 1.0000\n",
      "Epoch 17/100\n",
      "1000/1000 [==============================] - 1s 616us/step - loss: 0.0290 - acc: 1.0000\n",
      "Epoch 18/100\n",
      "1000/1000 [==============================] - 1s 580us/step - loss: 0.0262 - acc: 1.0000\n",
      "Epoch 19/100\n",
      "1000/1000 [==============================] - 1s 605us/step - loss: 0.0237 - acc: 1.0000\n",
      "Epoch 20/100\n",
      "1000/1000 [==============================] - 1s 660us/step - loss: 0.0216 - acc: 1.0000\n",
      "Epoch 21/100\n",
      "1000/1000 [==============================] - 1s 612us/step - loss: 0.0197 - acc: 1.0000\n",
      "Epoch 22/100\n",
      "1000/1000 [==============================] - 1s 590us/step - loss: 0.0181 - acc: 1.0000\n",
      "Epoch 23/100\n",
      "1000/1000 [==============================] - 1s 576us/step - loss: 0.0166 - acc: 1.0000\n",
      "Epoch 24/100\n",
      "1000/1000 [==============================] - 1s 613us/step - loss: 0.0153 - acc: 1.0000\n",
      "Epoch 25/100\n",
      "1000/1000 [==============================] - 1s 581us/step - loss: 0.0141 - acc: 1.0000\n",
      "Epoch 26/100\n",
      "1000/1000 [==============================] - 1s 590us/step - loss: 0.0131 - acc: 1.0000\n",
      "Epoch 27/100\n",
      "1000/1000 [==============================] - 1s 575us/step - loss: 0.0121 - acc: 1.0000\n",
      "Epoch 28/100\n",
      "1000/1000 [==============================] - 1s 583us/step - loss: 0.0113 - acc: 1.0000\n",
      "Epoch 29/100\n",
      "1000/1000 [==============================] - 1s 578us/step - loss: 0.0105 - acc: 1.0000\n",
      "Epoch 30/100\n",
      "1000/1000 [==============================] - 1s 554us/step - loss: 0.0098 - acc: 1.0000\n",
      "Epoch 31/100\n",
      "1000/1000 [==============================] - 1s 582us/step - loss: 0.0091 - acc: 1.0000\n",
      "Epoch 32/100\n",
      "1000/1000 [==============================] - 1s 587us/step - loss: 0.0085 - acc: 1.0000\n",
      "Epoch 33/100\n",
      "1000/1000 [==============================] - 1s 613us/step - loss: 0.0080 - acc: 1.0000\n",
      "Epoch 34/100\n",
      "1000/1000 [==============================] - 1s 578us/step - loss: 0.0075 - acc: 1.0000\n",
      "Epoch 35/100\n",
      "1000/1000 [==============================] - 1s 559us/step - loss: 0.0070 - acc: 1.0000\n",
      "Epoch 36/100\n",
      "1000/1000 [==============================] - 1s 583us/step - loss: 0.0066 - acc: 1.0000\n",
      "Epoch 37/100\n",
      "1000/1000 [==============================] - 1s 539us/step - loss: 0.0062 - acc: 1.0000\n",
      "Epoch 38/100\n",
      "1000/1000 [==============================] - 1s 590us/step - loss: 0.0058 - acc: 1.0000\n",
      "Epoch 39/100\n",
      "1000/1000 [==============================] - 1s 608us/step - loss: 0.0055 - acc: 1.0000\n",
      "Epoch 40/100\n",
      "1000/1000 [==============================] - 1s 568us/step - loss: 0.0052 - acc: 1.0000\n",
      "Epoch 41/100\n",
      "1000/1000 [==============================] - 1s 577us/step - loss: 0.0049 - acc: 1.0000\n",
      "Epoch 42/100\n",
      "1000/1000 [==============================] - 1s 580us/step - loss: 0.0046 - acc: 1.0000\n",
      "Epoch 43/100\n",
      "1000/1000 [==============================] - 1s 564us/step - loss: 0.0043 - acc: 1.0000\n",
      "Epoch 44/100\n",
      "1000/1000 [==============================] - 1s 561us/step - loss: 0.0041 - acc: 1.0000\n",
      "Epoch 45/100\n",
      "1000/1000 [==============================] - 1s 592us/step - loss: 0.0039 - acc: 1.0000\n",
      "Epoch 46/100\n",
      "1000/1000 [==============================] - 1s 552us/step - loss: 0.0036 - acc: 1.0000\n",
      "Epoch 47/100\n",
      "1000/1000 [==============================] - 1s 584us/step - loss: 0.0034 - acc: 1.0000\n",
      "Epoch 48/100\n",
      "1000/1000 [==============================] - 1s 560us/step - loss: 0.0033 - acc: 1.0000\n",
      "Epoch 49/100\n",
      "1000/1000 [==============================] - 1s 552us/step - loss: 0.0031 - acc: 1.0000\n",
      "Epoch 50/100\n",
      "1000/1000 [==============================] - 1s 580us/step - loss: 0.0029 - acc: 1.0000\n",
      "Epoch 51/100\n",
      "1000/1000 [==============================] - 1s 562us/step - loss: 0.0028 - acc: 1.0000\n",
      "Epoch 52/100\n",
      "1000/1000 [==============================] - 1s 595us/step - loss: 0.0026 - acc: 1.0000\n",
      "Epoch 53/100\n",
      "1000/1000 [==============================] - 1s 585us/step - loss: 0.0025 - acc: 1.0000\n",
      "Epoch 54/100\n",
      "1000/1000 [==============================] - 1s 605us/step - loss: 0.0023 - acc: 1.0000\n",
      "Epoch 55/100\n",
      "1000/1000 [==============================] - 1s 601us/step - loss: 0.0022 - acc: 1.0000\n",
      "Epoch 56/100\n",
      "1000/1000 [==============================] - 1s 593us/step - loss: 0.0021 - acc: 1.0000\n",
      "Epoch 57/100\n",
      "1000/1000 [==============================] - 1s 580us/step - loss: 0.0020 - acc: 1.0000\n",
      "Epoch 58/100\n",
      "1000/1000 [==============================] - 1s 606us/step - loss: 0.0019 - acc: 1.0000\n",
      "Epoch 59/100\n",
      "1000/1000 [==============================] - 1s 585us/step - loss: 0.0018 - acc: 1.0000\n",
      "Epoch 60/100\n",
      "1000/1000 [==============================] - 1s 598us/step - loss: 0.0017 - acc: 1.0000\n",
      "Epoch 61/100\n",
      "1000/1000 [==============================] - 1s 566us/step - loss: 0.0016 - acc: 1.0000\n",
      "Epoch 62/100\n",
      "1000/1000 [==============================] - 1s 586us/step - loss: 0.0015 - acc: 1.0000\n",
      "Epoch 63/100\n",
      "1000/1000 [==============================] - 1s 582us/step - loss: 0.0015 - acc: 1.0000\n",
      "Epoch 64/100\n",
      "1000/1000 [==============================] - 1s 575us/step - loss: 0.0014 - acc: 1.0000\n",
      "Epoch 65/100\n",
      "1000/1000 [==============================] - 1s 576us/step - loss: 0.0013 - acc: 1.0000\n",
      "Epoch 66/100\n",
      "1000/1000 [==============================] - 1s 592us/step - loss: 0.0012 - acc: 1.0000\n",
      "Epoch 67/100\n",
      "1000/1000 [==============================] - 1s 599us/step - loss: 0.0012 - acc: 1.0000\n",
      "Epoch 68/100\n",
      "1000/1000 [==============================] - 1s 536us/step - loss: 0.0011 - acc: 1.0000\n",
      "Epoch 69/100\n",
      "1000/1000 [==============================] - 1s 535us/step - loss: 0.0011 - acc: 1.0000\n",
      "Epoch 70/100\n",
      "1000/1000 [==============================] - 1s 528us/step - loss: 0.0010 - acc: 1.0000\n",
      "Epoch 71/100\n",
      "1000/1000 [==============================] - 1s 534us/step - loss: 9.6827e-04 - acc: 1.0000\n",
      "Epoch 72/100\n",
      "1000/1000 [==============================] - 1s 612us/step - loss: 9.2040e-04 - acc: 1.0000\n",
      "Epoch 73/100\n",
      "1000/1000 [==============================] - 1s 675us/step - loss: 8.7512e-04 - acc: 1.0000\n",
      "Epoch 74/100\n",
      "1000/1000 [==============================] - 1s 619us/step - loss: 8.3212e-04 - acc: 1.0000\n",
      "Epoch 75/100\n",
      "1000/1000 [==============================] - 1s 619us/step - loss: 7.9122e-04 - acc: 1.0000\n",
      "Epoch 76/100\n",
      "1000/1000 [==============================] - 1s 742us/step - loss: 7.5247e-04 - acc: 1.0000\n",
      "Epoch 77/100\n",
      "1000/1000 [==============================] - 1s 615us/step - loss: 7.1565e-04 - acc: 1.0000\n",
      "Epoch 78/100\n",
      "1000/1000 [==============================] - 1s 590us/step - loss: 6.8077e-04 - acc: 1.0000\n",
      "Epoch 79/100\n",
      "1000/1000 [==============================] - 1s 653us/step - loss: 6.4748e-04 - acc: 1.0000\n",
      "Epoch 80/100\n",
      "1000/1000 [==============================] - 1s 691us/step - loss: 6.1599e-04 - acc: 1.0000\n",
      "Epoch 81/100\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1000/1000 [==============================] - 1s 626us/step - loss: 5.8603e-04 - acc: 1.0000\n",
      "Epoch 82/100\n",
      "1000/1000 [==============================] - 1s 590us/step - loss: 5.5753e-04 - acc: 1.0000\n",
      "Epoch 83/100\n",
      "1000/1000 [==============================] - 1s 592us/step - loss: 5.3051e-04 - acc: 1.0000\n",
      "Epoch 84/100\n",
      "1000/1000 [==============================] - 1s 635us/step - loss: 5.0479e-04 - acc: 1.0000\n",
      "Epoch 85/100\n",
      "1000/1000 [==============================] - 1s 618us/step - loss: 4.8034e-04 - acc: 1.0000\n",
      "Epoch 86/100\n",
      "1000/1000 [==============================] - 1s 607us/step - loss: 4.5714e-04 - acc: 1.0000\n",
      "Epoch 87/100\n",
      "1000/1000 [==============================] - 1s 589us/step - loss: 4.3503e-04 - acc: 1.0000\n",
      "Epoch 88/100\n",
      "1000/1000 [==============================] - 1s 557us/step - loss: 4.1406e-04 - acc: 1.0000\n",
      "Epoch 89/100\n",
      "1000/1000 [==============================] - 1s 523us/step - loss: 3.9407e-04 - acc: 1.0000\n",
      "Epoch 90/100\n",
      "1000/1000 [==============================] - 1s 514us/step - loss: 3.7510e-04 - acc: 1.0000\n",
      "Epoch 91/100\n",
      "1000/1000 [==============================] - 1s 529us/step - loss: 3.5704e-04 - acc: 1.0000\n",
      "Epoch 92/100\n",
      "1000/1000 [==============================] - 1s 527us/step - loss: 3.3987e-04 - acc: 1.0000\n",
      "Epoch 93/100\n",
      "1000/1000 [==============================] - 1s 557us/step - loss: 3.2352e-04 - acc: 1.0000\n",
      "Epoch 94/100\n",
      "1000/1000 [==============================] - 1s 566us/step - loss: 3.0800e-04 - acc: 1.0000\n",
      "Epoch 95/100\n",
      "1000/1000 [==============================] - 1s 567us/step - loss: 2.9318e-04 - acc: 1.0000\n",
      "Epoch 96/100\n",
      "1000/1000 [==============================] - 1s 569us/step - loss: 2.7912e-04 - acc: 1.0000\n",
      "Epoch 97/100\n",
      "1000/1000 [==============================] - 1s 552us/step - loss: 2.6575e-04 - acc: 1.0000\n",
      "Epoch 98/100\n",
      "1000/1000 [==============================] - 1s 541us/step - loss: 2.5299e-04 - acc: 1.0000\n",
      "Epoch 99/100\n",
      "1000/1000 [==============================] - 1s 533us/step - loss: 2.4086e-04 - acc: 1.0000\n",
      "Epoch 100/100\n",
      "1000/1000 [==============================] - 1s 543us/step - loss: 2.2932e-04 - acc: 1.0000\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<keras.callbacks.History at 0xb402cd6a0>"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y.reshape((-1,1))\n",
    "final_input.reshape((-1,1))\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "from numpy import *\n",
    "\n",
    "model = Sequential()\n",
    "model.add(Dense(8,input_dim = 1 + len(list(new_dict2.keys()))))\n",
    "model.add(Dense(8 , activation = 'sigmoid'))\n",
    "model.add(Dense(1 , activation = 'sigmoid'))\n",
    "\n",
    "model.compile(loss = 'binary_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'])\n",
    "\n",
    "model.fit(final_input,y,nb_epoch = 100 ,batch_size = 10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 120,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "81.175\n"
     ]
    }
   ],
   "source": [
    "m = int(np.random.random(1)*10000)\n",
    "test = np.array(df[list(df.columns)[2]])[m]\n",
    "test = np.array(final(test))\n",
    "test = test.reshape((1,-1))\n",
    "\n",
    "test_data = np.array(df[list(df.columns)[2]])[1000:9000]\n",
    "y_pred = []\n",
    "for review in test_data:\n",
    "    review = np.array(final(review))\n",
    "    review = review.reshape((-1,1))\n",
    "    #print(model.predict(review.T))\n",
    "    if model.predict(review.T)>0.5:\n",
    "        result = 1\n",
    "    else :\n",
    "        result = 0\n",
    "    y_pred.append(result)\n",
    "y_pred = np.array(y_pred)\n",
    "\n",
    "y_real = np.array(df[list(df.columns)[1]])[1000:9000]\n",
    "\n",
    "from sklearn.metrics import accuracy_score\n",
    "print(accuracy_score(y_real,y_pred)*100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 99,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1"
      ]
     },
     "execution_count": 99,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['sentiment'][m]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\"I gave it an 8 only because it had received such low votes... this is definitely really about a 5.5..... Ummm.. it was kind of bloody, had likeable, shallow characters, and it had some really hot babes in it. I like the eclectic killer, because he didn't kill people the same way everytime... that sometimes gets old.\""
      ]
     },
     "execution_count": 100,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['review'][m]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
